name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 22 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_01d91434-9d8f-4239-ac89-acd6815054b4 }}
          GH_TOKEN: ${{ secrets.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 }}
